INHERIT: active-handout.yml

site_name: Machine Learning

extra_javascript:
  - js/tabs.js
  - js/termynal.js
  - js/custom.js

extra_css:
    - css/termynal.css

nav:
  - 'Home': index.md
  - Content:
    - machine_learning_common/01-intro/intro.md
